"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Bell, Boxes, ChartNoAxesCombined, ClipboardList, FileText, LayoutDashboard, Menu, Users, X, Zap } from "lucide-react";
import { useState } from "react";
import { Brand } from "./brand";
import { ThemeToggle } from "./theme-toggle";
import { cn } from "@/lib/utils";
const navigation = [{ href: "/dashboard", label: "Command Center", icon: LayoutDashboard }, { href: "/action-center", label: "AI Action Center", icon: Zap }, { href: "/inventory", label: "Inventory", icon: Boxes }, { href: "/invoices", label: "Invoices", icon: FileText }, { href: "/customers", label: "Customers", icon: Users }, { href: "/reports", label: "Reports", icon: ChartNoAxesCombined }, { href: "/agent-logs", label: "Agent Logs", icon: ClipboardList }];
export function AppShell({ children }: { children: React.ReactNode }) { const [open, setOpen] = useState(false); const pathname = usePathname(); const sidebar = <aside className="flex h-full w-72 flex-col border-r bg-white px-4 py-5 dark:bg-[#0b1220]"><Brand/><nav className="mt-10 space-y-1">{navigation.map(({href,label,icon: Icon}) => <Link key={href} onClick={() => setOpen(false)} href={href} className={cn("flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium transition", pathname === href ? "bg-blue-600 text-white shadow-lg shadow-blue-500/20" : "text-slate-500 hover:bg-slate-100 hover:text-slate-900 dark:hover:bg-slate-800 dark:hover:text-white")}><Icon size={18}/>{label}</Link>)}</nav><div className="mt-auto rounded-2xl bg-gradient-to-br from-blue-600 to-blue-700 p-4 text-white"><p className="text-sm font-semibold">Need a hand?</p><p className="mt-1 text-xs text-blue-100">Your business assistant is always here.</p><button className="mt-3 text-xs font-bold">Contact support →</button></div></aside>;
return <div className="min-h-screen"><div className="fixed inset-y-0 left-0 z-40 hidden lg:block">{sidebar}</div>{open && <div className="fixed inset-0 z-50 lg:hidden"><button aria-label="Close menu" className="absolute inset-0 bg-slate-950/40" onClick={() => setOpen(false)}/><div className="relative h-full shadow-2xl">{sidebar}<button className="absolute right-4 top-5 text-slate-500" onClick={() => setOpen(false)}><X/></button></div></div>}<main className="lg:pl-72"><header className="sticky top-0 z-30 flex h-20 items-center justify-between border-b bg-slate-50/80 px-5 backdrop-blur dark:bg-[#080d18]/80 sm:px-8"><button className="lg:hidden" onClick={() => setOpen(true)}><Menu/></button><div className="hidden lg:block"><p className="text-xs font-medium text-slate-400">VyapaarSathi AI</p><p className="text-sm font-semibold">Good morning, Akshita 👋</p></div><div className="ml-auto flex items-center gap-2"><ThemeToggle/><button className="relative grid h-9 w-9 place-items-center rounded-xl text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800"><Bell size={18}/><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-emerald-500"/></button><div className="ml-2 grid h-9 w-9 place-items-center rounded-xl bg-emerald-100 text-xs font-bold text-emerald-700">AK</div></div></header><div className="p-5 sm:p-8">{children}</div></main></div>; }
