"use client";
import Link from "next/link";
import { zodResolver } from "@hookform/resolvers/zod";
import { Eye, EyeOff, Loader2 } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
const schema = z.object({ name:z.string().min(2,"Please enter your name").optional(), email:z.string().email("Enter a valid email"), password:z.string().min(8,"Password must be at least 8 characters") });
type Values = z.infer<typeof schema>;
export function AuthForm({ signup=false }: { signup?:boolean }) { const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const {register,handleSubmit,formState:{errors}}=useForm<Values>({resolver:zodResolver(schema)}); const submit=async()=>{setLoading(true); await new Promise(r=>setTimeout(r,600)); window.location.href="/dashboard"}; return <form onSubmit={handleSubmit(submit)} className="mt-7 space-y-4">{signup&&<Field label="Full name" error={errors.name?.message}><input {...register("name")} placeholder="Your full name"/></Field>}<Field label="Work email" error={errors.email?.message}><input {...register("email")} type="email" placeholder="you@company.com"/></Field><Field label="Password" error={errors.password?.message}><div className="relative"><input {...register("password")} type={show?"text":"password"} placeholder="Minimum 8 characters"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-3 text-slate-400">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></Field><button disabled={loading} className="btn-primary w-full py-3">{loading?<Loader2 className="animate-spin" size={17}/>:signup?"Create my account":"Sign in"}</button><p className="text-center text-sm text-slate-500">{signup?"Already have an account? ":"New to VyapaarSathi? "}<Link className="font-semibold text-blue-600" href={signup?"/login":"/signup"}>{signup?"Sign in":"Create an account"}</Link></p></form> }
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="block text-sm font-medium">{label}<div className="mt-1.5 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:bg-transparent [&_input]:px-3 [&_input]:py-3 [&_input]:text-sm [&_input]:outline-none [&_input]:focus:border-blue-500 [&_input]:focus:ring-2 [&_input]:focus:ring-blue-100">{children}</div>{error&&<span className="mt-1 block text-xs text-rose-500">{error}</span>}</label>}
