create extension if not exists "pgcrypto";
create type public.inventory_status as enum ('in_stock','low_stock','out_of_stock');
create type public.invoice_status as enum ('draft','sent','paid','overdue','cancelled');
create type public.reminder_status as enum ('pending','completed','dismissed');
create type public.priority as enum ('low','medium','high');
create type public.log_status as enum ('pending','success','failed');

create table public.users (id uuid primary key references auth.users(id) on delete cascade, email text not null, full_name text, business_name text, phone text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.products (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, name text not null, sku text, category text, unit text not null default 'unit', quantity integer not null default 0 check(quantity >= 0), reorder_level integer not null default 0 check(reorder_level >= 0), cost_price numeric(12,2) not null check(cost_price >= 0), selling_price numeric(12,2) not null check(selling_price >= 0), status public.inventory_status not null default 'in_stock', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, sku));
create table public.customers (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, name text not null, email text, phone text, address text, gstin text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.invoices (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, invoice_number text not null, customer_id uuid references public.customers(id) on delete set null, issue_date timestamptz not null, due_date timestamptz, subtotal numeric(12,2) not null check(subtotal >= 0), tax_amount numeric(12,2) not null default 0 check(tax_amount >= 0), total_amount numeric(12,2) not null check(total_amount >= 0), status public.invoice_status not null default 'draft', notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, invoice_number));
create table public.sales (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, invoice_id uuid references public.invoices(id) on delete set null, product_id uuid references public.products(id) on delete set null, customer_id uuid references public.customers(id) on delete set null, quantity numeric(12,3) not null check(quantity > 0), unit_price numeric(12,2) not null check(unit_price >= 0), total_amount numeric(12,2) not null check(total_amount >= 0), sale_date timestamptz not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.expenses (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, title text not null, category text not null, amount numeric(12,2) not null check(amount >= 0), expense_date timestamptz not null, payment_method text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.reminders (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, title text not null, description text, due_at timestamptz not null, status public.reminder_status not null default 'pending', priority public.priority not null default 'medium', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.agent_logs (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, action text not null, input jsonb, output jsonb, status public.log_status not null default 'pending', metadata jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index on public.products(user_id); create index on public.customers(user_id); create index on public.invoices(user_id, status); create index on public.sales(user_id, sale_date); create index on public.expenses(user_id, expense_date); create index on public.reminders(user_id, due_at); create index on public.agent_logs(user_id, created_at desc);
alter table public.users enable row level security; alter table public.products enable row level security; alter table public.customers enable row level security; alter table public.invoices enable row level security; alter table public.sales enable row level security; alter table public.expenses enable row level security; alter table public.reminders enable row level security; alter table public.agent_logs enable row level security;
create policy "Users access own data" on public.users for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "Products access own data" on public.products for all using (auth.uid() = user_id) with check (auth.uid() = user_id); create policy "Customers access own data" on public.customers for all using (auth.uid() = user_id) with check (auth.uid() = user_id); create policy "Invoices access own data" on public.invoices for all using (auth.uid() = user_id) with check (auth.uid() = user_id); create policy "Sales access own data" on public.sales for all using (auth.uid() = user_id) with check (auth.uid() = user_id); create policy "Expenses access own data" on public.expenses for all using (auth.uid() = user_id) with check (auth.uid() = user_id); create policy "Reminders access own data" on public.reminders for all using (auth.uid() = user_id) with check (auth.uid() = user_id); create policy "Logs access own data" on public.agent_logs for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
